#!/bin/bash

set -e

cd "$(dirname "$0")"

fail() {
  echo "$1" >&2
  exit 1
}

SHA1=$(git ls-remote "https://github.com/overview/overview-server.git" "$1" | cut -f1)

git diff-index --quiet HEAD -- || fail "You have local changes. Commit or reset before running $0."

[ -n "$SHA1" ] || fail "Usage: $0 valid-overview-server-ref"

sed -i -e "s/[0-9a-f]\\{40\\}\\.zip/$SHA1.zip/" overview-base/Dockerfile
git commit -m "Release $SHA1" overview-base/Dockerfile
git push
