#!/bin/ash

mkdir -p /etc/traefik/parts
cp /traefik/traefik.yml /etc/traefik/
cp /traefik/by-port.yml /etc/traefik/parts/

if [ -n "$OV_DOMAIN_NAME" ]; then
  # Set env vars that are used in /etc/traefik/parts/ssl.yml
  # https://docs.traefik.io/providers/file/#go-templating
  export DOMAIN_NAME_START="$(echo "$OV_DOMAIN_NAME" | cut -d. -f1)"
  export DOMAIN_PARENT="$(echo "$OV_DOMAIN_NAME" | cut -d. -f2-999)"
  cp /traefik/ssl.yml /etc/traefik/parts/
fi

if [ ! -d /var/lib/acme ]; then
  echo " ***/var/lib/acme/ does not exist! ***" >&2
  echo >&2
  echo "This suggests SSL keys aren't being saved. Every time you restart, " >&2
  echo "new keys will be created. Overview users may notice SSL errors." >&2
  echo >&2
  echo "To fix this, mount a Docker volume at '/var/lib/acme/'." >&2
  mkdir -p /var/lib/acme
fi

exec traefik
